name: PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pytest
        run: pytest -vrP --alluredir=build/allure-results

      - name: Build Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      # - name: Post the link to the report
      #   if: always()
      #   uses: Sibz/github-status-action@v1
      #   with: 
      #       authToken: ${{secrets.GITHUB_TOKEN}}
      #       context: 'Test report'
      #       state: 'success'
      #       sha: ${{ github.event.pull_request.head.sha }}
      #       target_url: https://strongin-qa.github.io/My-python-studies/${{ github.run_number }}